service: processProductionCurveBefore2023
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-plugin-include-dependencies

package:
  patterns:
    - node_modules/**

custom:
  prune:
    automatic: true
    number: 3

functions:
  process_curve_production_before_2023:
    handler: handler.process_curve_production_before_2023